### ISSUE TITLE
失败的

### ISSUE THREAD

**Issue by lilei-John** [enthusiasticgeek/gstreamer-rtsp-ssl-example#2]
/home/share/nfs-server/gstreamer-rtsp-ssl-example-master/digital_certificates/gst_ssl_ca.pem
/home/share/nfs-server/gstreamer-rtsp-ssl-example-master/digital_certificates/gst_ssl_cert.pem
/home/share/nfs-server/gstreamer-rtsp-ssl-example-master/digital_certificates/gst_ssl_cert_decrypt.key
8554
vod/mp4:CustomerLove.mp4
user
password
Playing: rtsps://127.0.0.1:8554/vod/mp4:CustomerLove.mp4
Error: Could not open resource for reading.
End of the Streaming... ending the playback
Eliminating Pipeline

**Comment by enthusiasticgeek** [comment]
In my case my mount point is /test in conf file. Have you tried something simple like that rather than big name with colon?

**Comment by enthusiasticgeek** [comment]
Btw you need to replace videotestsrc with filesrc and appropriate encoding in server code.

Although I haven't tested below pipeline it should be easy to tweak for your needs.
On server side the code change is

`gst_rtsp_media_factory_set_launch (factory, "( "
                                       "filesrc location=/CustomerLove.mp4 qtdemux name=demux demux. ! h264parse config-interval=10 ! queue ! mux. mpegtsmux name=mux ! rtpmp2tpay ! "
                                       "x264enc ! rtph264pay name=pay0 pt=96 "
                                       "demux. ! aacparse ! queue ! mux. ! rtppcmapay name=pay1 pt=97 " ")");`

Similarly, on the client side the code changes will need to match these elements on the decoding pipeline.
