### ISSUE TITLE
Help in implementing CA verification

### ISSUE THREAD

**Issue by AnanduKE** [enthusiasticgeek/gstreamer-rtsp-ssl-example#4]
Can some one please provide support in implementing CA verification also . By analysing the code it shows that any key can be used. 
Are we using password and username to securely passing the public keys ?

**Comment by enthusiasticgeek** [comment]
The private key is not password protected for this example, if that is what you are referring to. The stream username and password  is not related to SSL CA and certs. Public key is meant for public consumption and private key is secretly stored. I guess I am not sure what you are asking given your statement "Are we using password and username to securely passing the public keys ?".
