### ISSUE TITLE
Where to put video path

### ISSUE THREAD

**Issue by jcraffael** [enthusiasticgeek/gstreamer-rtsp-ssl-example#5]
Hello! Thank you for the project above all! 
I'd like to ask how to push a video from client and make server receive or vice verso if I have a video for this purpose? Should I do that by using some command line arguments?
Thank you!

**Comment by enthusiasticgeek** [comment]
```
    factory = gst_rtsp_media_factory_new ();
    
    gst_rtsp_media_factory_set_launch (factory, "( "
                                       "videotestsrc ! video/x-raw,width=352,height=288,framerate=15/1 ! "
                                       "x264enc ! rtph264pay name=pay0 pt=96 "
                                       "audiotestsrc ! audio/x-raw,rate=8000 ! "
                                       "alawenc ! rtppcmapay name=pay1 pt=97 " ")");
```

So here instead of `videotestsrc` you may replace with `filesrc` https://gstreamer.freedesktop.org/documentation/coreelements/filesrc.html?gi-language=c
